### ISSUE TITLE
Modal Consulenze

### ISSUE THREAD

**Issue by leonardodemarco00** [omardeangelis/hpv4learning#156]

**Comment by omardeangelis** [comment]
In questa issue @leonardodemarco00  intendi creare tutta la UI del Modal ? 
Che ne dici se aggiungessimo nella folder `components` una folder Modal dove andiamo a crearci questa serie di componenti ?
Così fatti una volta, dovrebbero essere apposto per sempre i modal

```
<Modal/>
<ModalOverlay/>
<ModalCloseButtons/>
<ModalBackButtons/> 
<ModalHeader>
<ModalBody>
<ModalFooter/>
```

Possiamo anche spezzarli in singole PR questi componenti e in singole issue ?

**Comment by omardeangelis** [comment]
Forse sarebbe utile anche inserire un Modal Loader, magari material UI ha uno spinner customizzabile

**Comment by leonardodemarco00** [comment]
@omardeangelis  Si pensavo di creare i vari styled components in un file ed esportarli tutti da li, tanto alla fine sono tutti Box con grandezze diverse

Per il loader mui ha sicuramente qualcosa, penso sia spinner che progress bar

**Comment by omardeangelis** [comment]
@leonardodemarco00 valuterei di installare styled-system per provare creare dei component furbi e poter usare davvero `css` e se sia quella la soluzione.

**Comment by omardeangelis** [comment]
@leonardodemarco00 se cerchi reference chackra ha in questo file praticamente tutti questi component 
https://github.com/chakra-ui/chakra-ui/blob/next/packages/modal/src/modal.tsx

**Comment by omardeangelis** [comment]
Teniamo qua la discussione sulle props dei modal. 

Comunque a parte di mettere la props onClose sul modal altre che sia necessarie non me ne vengono. 

Forse creerei un ModalContext con cui subito sotto al modal a cui passiamo anche a lui onClose dal modal così tutto quello che è dentro il modal può accedere a questa funzione.
